# Generated by Django 2.1.1 on 2018-09-28 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('a_title', models.CharField(max_length=30, verbose_name='文章标题')),
                ('a_desc', models.CharField(max_length=100, verbose_name='文章描述')),
                ('a_content', models.TextField(verbose_name='文章内容')),
                ('a_tag', models.CharField(max_length=30, verbose_name='标签')),
                ('a_status', models.BooleanField(default=1, verbose_name='发布状态')),
            ],
            options={
                'db_table': 't_article',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('c_title', models.CharField(max_length=30, verbose_name='标题')),
                ('c_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='home.CategoryModel', verbose_name='自我关联')),
            ],
            options={
                'db_table': 't_category',
            },
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='a_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.CategoryModel', verbose_name='article'),
        ),
    ]
